version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND_URL=redis://redis:6379/0
      - WHISPER_CLI=/app/whisper.cpp/build/bin/whisper-cli
      - WHISPER_MODELS_DIR=/app/whisper.cpp/models
      - MODEL=ggml-medium-q8_0.bin
      - UPLOAD_DIR=/app/uploads
      - METADATA_FILE=/app/metadata.json
      - API_KEY=your-secret-api-key
      - MAX_AGE_SECONDS=86400
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - redis
    command: uvicorn app:app --host 0.0.0.0 --port 8000

  worker:
    build: .
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND_URL=redis://redis:6379/0
      - WHISPER_CLI=/app/whisper.cpp/build/bin/whisper-cli
      - WHISPER_MODELS_DIR=/app/whisper.cpp/models
      - MODEL=ggml-medium-q8_0.bin
      - UPLOAD_DIR=/app/uploads
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - redis
    command: celery -A celery_worker.celery_app worker -l info
